#!/usr/bin/env bash
# install Nginx and write Hello world at the root
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /usr/share/nginx/html/index.html
sudo service nginx start
