#!/usr/bin/env bash
# script to resolve localhost to 127.0.0.2 and facebook to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i '/localhost/s/.1/.2/' ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
