#!/usr/bin/env bash
# make nginx run as nginx user and nginx should listen on 8080 port
pkill apache2
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
